services:
  - type: web
    name: o2-whatsapp-bot
    env: node
    buildCommand: yarn install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
